server:
  port: 9090
  error:
    whitelabel:
      enabled: false


spring:
  profiles:
    active: local

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  #  ANSI
  output:
    ansi:
      enabled: ALWAYS

  #  DEVTOOLS
  devtools:
    restart:
      enabled: true

# LOGGING
logging:
  level:
    root: error
    com.joje.daisy: debug

# JWT
jwt:
  secret: bWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGk=
  access-token-expire: 60
  refresh-token-expire: 120


---
# LOCAL
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://apm-test.chd3n4lm1fmm.ap-northeast-2.rds.amazonaws.com/daisy
    username: ENC(0/cMqN7QTjW4EQuz4sraGg==)
    password: ENC(n9rDws6yHK8quZHqh6O2K3O/YjkiKP5z)